mode: auto

#头像
avatar:
  enable: true
  url: https://s2.loli.net/2022/05/31/U5JQfLTbqk3Cv9P.jpg
  rounded: true
  opacity: 1
  mickey_mouse: false
  status:
    enable: true
    emoji: 🌈
    message: 端午安康！

reward:
  enable: true
  comment: 请不要给我打钱，我可不会还给你呦
  methods:
    - name: 支付宝
      path: https://s2.loli.net/2022/06/03/tCqIUTsexGL63ok.jpg
      color: '#00A3EE'
      icon: ri:alipay-line
    - name: QQ 支付
      path: https://s2.loli.net/2022/06/03/eKinQN4z9RqgrYy.png
      color: '#12B7F5'
      icon: ri:qq-line
    - name: 微信支付
      path: https://s2.loli.net/2022/06/03/gMshOJ4fbkDGETX.png
      color: '#2DC100'
      icon: ri:wechat-pay-line

comment:
  candidates:
    - waline
    # - giscus
  tips:
    - 如果您有任何关于博客内容的相关讨论，欢迎前往 <a href="https://github.com/YunYouJun/yunyoujun.github.io/discussions" target="_blank">GitHub Discussions</a> 与我交流。

waline:
  enable: false
  serverURL: https://waline.yunyoujun.cn
  visitor: true
  comment: true
  emoji:
    - https://fastly.jsdelivr.net/gh/walinejs/emojis@latest/bilibili/
    - https://fastly.jsdelivr.net/gh/walinejs/emojis@latest/weibo/
    - https://fastly.jsdelivr.net/gh/walinejs/emojis@latest/qq/
  locale:
    placeholder: 填写邮箱，可以收到回复通知哦～  (建议使用QQ邮箱)
  requiredMeta: [nick]

github_issues:
  enable: false

github_discussions:
  enable: false

disqusjs:
  enable: false
  shortname: yunyoujun
  apikey: ouoGQCaamOKdJgyZU5DKcpFnRIg3SNzvk0nwygPtlcTRJuE68c8igvrZGW4wAJoN

# https://github.com/laymonage/giscus
giscus:
  enable: false
  repo: YunYouJun/yunyoujun.github.io
  repo-id:
  category-id:
  mapping: pathname
  reactions-enabled: 1
  emit-metadata: 0
  theme: light

footer:
  since: 2022
  icon:
    url: 
    title: 柯尔鸭的赞助者们
  beian:
    enable: false
    icp: 苏ICP备17038157号
  live_time:
    enable: true
    prefix: 本博客已萌萌哒地运行了
    suffix: (●'◡'●)
    start_time: '2022-05-31T13:14:00'
  support:
    enable: false
    title: 又拍云
    link: https://www.upyun.com
    logo: https://cdn.yunyoujun.cn/img/logo/upyun-logo.png
    prefix: 本网站由
    suffix: 提供 CDN 加速
  custom_text:


engine_search:
  enable: false

# If you want to use it, you need config algolia appID in _config.yml!!!
# https://github.com/oncletom/hexo-algolia
algolia_search:
  enable: false
  # ...

google_analytics:
  enable: true
  id: G-1LL0D86CY9

google_adsense:
  enable: true
  client: ca-pub-2245427233262012

post_edit:
  enable: true
  url: https://github.com/YunYouJun/yunyoujun.github.io/tree/hexo/source/

albums:
  enable: true

girls:
  enable: true

#UI
banner:
  enable: true
  title: 很高兴遇见你
  border: true
  cloud:
    enable: true
    color: white
  go_down:
    enable: true
    icon: ri:arrow-down-s-line

wordcloud:
  enable: true

categories:
  杂项: 'CCFFFF'

#cdn:
  #pre: https://cdn.jsdelivr.net/gh/yzikey/yzikey.github.io@latest


pages:
  - name: 我的小伙伴们
    url: /links/
    icon: ph:address-book
    color: dodgerblue
  - name: 喜欢的动漫角色
    url: /girls/
    icon: ph:heart-duotone
    color: pink
  - name: 相册集
    url: /albums/
    icon: ph:camera-bold
    color: dimgray
    theme: wave
    password: hello

menu:
  custom:
    title: 留言板
    path: /about/comment
    icon: ri:clipboard-line
  home:
    path: /
    icon: ri:home-4-line
  list:
    - type: archives
      path: /archives/
      icon: ri:archive-line
    - type: categories
      path: /categories/
      icon: ri:folder-2-line
    - type: tags
      path: /tags/
      icon: ri:price-tag-3-line


cursor:
  enable: true

baidu_push: true

google_tagmanager:
  enable: true
  id: GTM-M9KWR9L

wordcount:
  enable: false

say:
  enable: true
  api: /data/sentences.json
  hitokoto:
    enable: false

mourn:
  enable: true
  days:
    - 4-4

pjax:
  enable: true

aplayer:
  global: true
  meting: true
  # https://github.com/metowolf/MetingJS/tree/v1.2#option
  widget:
    enable: true
    #id: 1364247901
    autoplay: true
    theme: '#2980b9'
    loop: all
    order: random
    preload: auto
    volume: 0.7
    mutex: true
    lrcType: 0
    listFolded: false
    listMaxHeight: 340px
    meting:
      enable: true
      id: 7466748299
      server: netease
      type: playlist

social:
#  - name: RSS
    # set rss in your root config
    # https://github.com/hexojs/hexo-generator-feed
#    link: /atom.xml # config.feed.path
#    icon: ri:rss-line
#    color: orange
  - name: GitHub
    link: https://github.com/yzikey
    icon: ri:github-line
    color: '#6e5494'
  - name: 微博
    link: https://weibo.com/u/7273500676
    icon: ri:weibo-line
    color: '#E6162D'
  - name: 网易云音乐
    link: https://music.163.com/#/user/home?id=1761720689
    icon: ri:netease-cloud-music-line
    color: '#C20C0C'
  - name: 知乎
    link: https://www.zhihu.com/people/du-zhu-23-39-93
    icon: ri:zhihu-line
    color: '#0084FF'
  - name: 哔哩哔哩
    link: https://space.bilibili.com/12848975
    icon: ri:bilibili-line
    color: '#FF8EB3'
#  - name: 微信公众号
#    link: https://cdn.yunyoujun.cn/img/about/white-qrcode-and-search.jpg
#    icon: ri:wechat-2-line
#    color: '#1AAD19'
#  - name: E-Mail
#    link: mailto:me@yunyoujun.cn
#    icon: ri:mail-line
#    color: '#8E71C1'

# pjax:
#   enable: true